version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
